name: Vardoger
main: moe.reno.vardoger.Vardoger
version: 1.0.1
api-version: 1.19
depend: [CommandAPI]
permissions:
  vardoger.spy:
    description: Notify when a player has met the threshold for a group
    default: op
  vardoger.admin:
    description: Notify admin messages
    default: op